// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetCurrentConfigPath():Promise<string>;

export function LoadConfigFromPath(arg1:string):Promise<config.Config>;

export function OpenFileDialog():Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveConfigAs(arg1:config.Config):Promise<string>;

export function TestRegex(arg1:string,arg2:string):Promise<boolean>;
